### ISSUE TITLE
Tens que conhecer os padrões FIG.

### ISSUE THREAD

**Issue by e200** [aicoutos/upload#1]
Conheça os padrões FIG: http://php-fig.org/.

Eles te vão ajudar muito no desenvolvimento de um bom framework.

**Comment by ghost** [comment]
obrigado @e200 . já conheço os padrões apenas não sigo eles por inteiro por uma questão de simplicidade, agilidade e legibilidade.

## PSR-1 x snake_case

está [comprovado](http://www.cs.kent.edu/~jmaletic/papers/ICPC2010-CamelCaseUnderScoreClouds.pdf) que o snake_case é muito mais legível que o camelCase. o próprio PHP segue o padrão snake_case em suas funções globais.

## PSR-2 x dependency injection
tenho planos de manter o framework com baixo acomplamento (loose coupling). por essa razão prefiro a injeção de dependências (dependency injection) ao invés da complexidade de um sistema de heranças.

**Comment by ghost** [comment]
Estou fechando essa issue pois a partir da versão 1.0.0 aplico os padrões PSR-0, PSR-1 e PSR-2. Em breve aplicarei eles em todos os pacotes do [Basic](https://github.com/aicoutos/basic). Obrigado @e200 .

**Comment by e200** [comment]
. Bom!!! Escolheu a Opção Certa! Já Ouviu Falar Do [StyleCI](http://styleci.io/)?
